# Router Flood Enhanced Configuration
# Educational DDoS Simulation Tool v3.0
# 
# ⚠️  EDUCATIONAL PURPOSES ONLY - LOCAL NETWORK TESTING
# Only use on networks you own or have explicit written permission to test

target:
  # Target configuration
  ip: "192.168.1.1"  # Must be private IP range (192.168.x.x, 10.x.x.x, 172.16-31.x.x)
  ports: [80, 443, 22, 53]  # Multiple ports for comprehensive testing
  
  # Protocol mix ratios (must sum to approximately 1.0)
  protocol_mix:
    udp_ratio: 0.60      # 60% UDP packets (most common in floods)
    tcp_syn_ratio: 0.25  # 25% TCP SYN packets
    tcp_ack_ratio: 0.05  # 5% TCP ACK packets
    icmp_ratio: 0.05     # 5% ICMP packets
    ipv6_ratio: 0.03     # 3% IPv6 packets
    arp_ratio: 0.02      # 2% ARP packets
  
  # Optional: Specify network interface (auto-detected if not set)
  interface: null  # e.g., "eth0", "wlan0", etc.

attack:
  # Attack parameters
  threads: 8                    # Number of concurrent threads (max: 100)
  packet_rate: 500             # Packets per second per thread (max: 10000)
  duration: 60                 # Duration in seconds (null for unlimited)
  packet_size_range: [64, 1400]  # Min and max packet sizes in bytes
  randomize_timing: true       # Add jitter to packet timing
  
  # Burst pattern configuration
  burst_pattern:
    # Choose one of the following patterns:
    
    # Sustained load (constant rate)
    Sustained:
      rate: 500
    
    # # Burst pattern (alternating high/low intensity)
    # Bursts:
    #   burst_size: 20
    #   burst_interval_ms: 1000
    
    # # Ramp pattern (gradually increasing load)
    # Ramp:
    #   start_rate: 100
    #   end_rate: 1000
    #   ramp_duration: 60

safety:
  # Safety and security limits
  max_threads: 100         # Maximum allowed threads
  max_packet_rate: 10000   # Maximum packets per second per thread
  require_private_ranges: true   # Only allow private IP targets
  enable_monitoring: true        # Enable system resource monitoring
  audit_logging: true           # Enable audit log creation
  dry_run: false               # Simulate without sending packets (safe testing)

monitoring:
  # Monitoring and reporting configuration
  stats_interval: 5           # Statistics reporting interval (seconds)
  system_monitoring: true     # Monitor CPU, memory usage
  export_interval: 30         # Export statistics every N seconds (null to disable)
  performance_tracking: true  # Track performance metrics

export:
  # Statistics export configuration
  enabled: true                 # Enable statistics export
  format: "Both"               # Export format: "Json", "Csv", or "Both"
  filename_pattern: "router_flood"  # Filename prefix for exports
  include_system_stats: true   # Include system resource stats in exports

# Example configurations for different testing scenarios:

# Home Router Testing (Conservative):
# attack:
#   threads: 2
#   packet_rate: 50
#   duration: 30

# Enterprise Testing (Moderate):
# attack:
#   threads: 8
#   packet_rate: 500
#   duration: 120

# High-Performance Testing (Aggressive):
# attack:
#   threads: 16
#   packet_rate: 2000
#   duration: 300