# Router Flood Configuration
# Educational DDoS Simulation Tool v0.0.1
# 
# ⚠️  EDUCATIONAL PURPOSES ONLY - LOCAL NETWORK TESTING
# Only use on networks you own or have explicit written permission to test

target:
  # Target configuration
  ip: "192.168.1.1"  # Must be private IP range (192.168.x.x, 10.x.x.x, 172.16-31.x.x)
  ports: [80, 443, 22, 53]  # Multiple ports for comprehensive testing
  
  # Protocol mix ratios (must sum to approximately 1.0)
  protocol_mix:
    udp_ratio: 0.25         # 25% UDP packets
    tcp_syn_ratio: 0.25     # 25% TCP SYN packets (new connections)
    tcp_ack_ratio: 0.15     # 15% TCP ACK packets (established connections)
    tcp_fin_ratio: 0.15     # 15% TCP FIN packets (graceful connection closes)
    tcp_rst_ratio: 0.10     # 10% TCP RST packets (connection resets)
    icmp_ratio: 0.10        # 10% ICMP packets
    custom_ratio: 0.0       # 0% custom packets (reserved for future use)
  
  # Optional: Specify network interface (auto-detected if not set)
  interface: null  # e.g., "eth0", "wlan0", etc.

attack:
  # Attack parameters
  threads: 8                    # Number of concurrent threads (max: 100)
  packet_rate: 500             # Packets per second per thread (max: 10000)
  duration: 60                 # Duration in seconds (null for unlimited)
  packet_size_range: [64, 1400]  # Min and max packet sizes in bytes
  randomize_timing: true       # Add jitter to packet timing
  
  # Burst pattern configuration (YAML tag format required)
  burst_pattern: !Sustained
    rate: 500
    
    # Alternative patterns (uncomment to use):
    # 
    # # Burst pattern (alternating high/low intensity)
    # burst_pattern: !Bursts
    #   burst_size: 20
    #   burst_interval_ms: 1000
    # 
    # # Ramp pattern (gradually increasing load)
    # burst_pattern: !Ramp
    #   start_rate: 100
    #   end_rate: 1000
    #   ramp_duration: 60

safety:
  # Safety and security limits
  max_threads: 100         # Maximum allowed threads
  max_packet_rate: 10000   # Maximum packets per second per thread
  require_private_ranges: true   # Only allow private IP targets
  enable_monitoring: true        # Enable system resource monitoring
  audit_logging: true           # Enable audit log creation
  dry_run: false               # Simulate without sending packets (safe testing)
  perfect_simulation: false     # Use 100% success rate in dry-run mode (no simulated failures)

monitoring:
  # Monitoring and reporting configuration
  stats_interval: 5           # Statistics reporting interval (seconds)
  system_monitoring: true     # Monitor CPU, memory usage
  export_interval: 30         # Export statistics every N seconds (null to disable)
  performance_tracking: true  # Track performance metrics

export:
  # Statistics export configuration
  enabled: true                 # Enable statistics export
  format: Both                 # Export format: Json, Csv, or Both
  filename_pattern: "router_flood"  # Filename prefix for exports
  include_system_stats: true   # Include system resource stats in exports

# Example configurations for different testing scenarios:

# Home Router Testing (Conservative):
# attack:
#   threads: 2
#   packet_rate: 50
#   duration: 30

# Enterprise Testing (Moderate):
# attack:
#   threads: 8
#   packet_rate: 500
#   duration: 120

# High-Performance Testing (Aggressive):
# attack:
#   threads: 16
#   packet_rate: 2000
#   duration: 300